# Generated by Django 4.2.5 on 2023-09-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.study_center')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('phone_number', models.CharField(max_length=100)),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.study_center')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
